### ISSUE TITLE
Readme needs to be updated:

### ISSUE THREAD

**Issue by neeraj-2** [edoriggio/covid19-daily-newsletter#2]
While reading the readme file, I found a grammatical error. The **"indox"** word needs to be updated I have attached a screenshot here.
Is this is a valid issue @edoriggio and @luca-de-felice . If it is, then what should come in place of it

![image](https://user-images.githubusercontent.com/56186425/94770739-03b35800-03d3-11eb-80cd-865dac556feb.png)

**Comment by edoriggio** [comment]
Thanks for noticing. I've assigned you the issue.

**Comment by neeraj-2** [comment]
> Thanks for noticing. I've assigned you the issue. In case you did not want it, let me know.

Thanks, @edoriggio but which **word** should replace it?

**Comment by edoriggio** [comment]
Yes, sorry. It should be "inbox"
